version: "3.5"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3030:80"
  mongo:
    image: "mongo:latest"
    command: mongod
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
  api:
    depends_on:
      - mongo
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    env_file:
      - .env
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    env_file:
      - .env
    volumes:
      - /app/node_modules
      - ./client:/app
